config/routes.rb
Arxivtab::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :documents, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/arxiv_search', to: 'static_pages#arxiv_search', via: 'get'

end

app/views/shared/_arxiv_search_form.html.erb
<%= form_for(:result) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :url, placeholder: "Insert search terms..." %>
  <%= f.submit "Search", :name => 'search_button', class: "btn btn-medium btn-primary pull-right" %>
  </div>
<% end %>
<% url = URI.parse('http://export.arxiv.org/api/query?search_query=all:electron&start=0&max_results=1') %>
<% res = Net::HTTP.get_response(url) %>
<div class="field">
  <% puts res.body %>
</div>

app/views/shared/_document_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@document, remote: remote, html: {role: :form, 'data-model' => 'document'}) do |g| %>

  <%#= render 'shared/error_messages', object: g.object %>

  <% if @document && @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% @document.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="form-group">
    <%#= g.label :url, class: 'control-label' %><br>
    <%= g.text_field :url, class: 'form-control' %>
    <%#= g.text_area :url, placeholder: "Add new document..." %>
    <span class="help-block"></span>
  </div>

  <%# Added Bootstrap classes %>
  <div class="actions">
    <%= g.submit 'Add', class: 'btn btn-default' %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object && object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items && @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", :name => 'post_button', class: "btn btn-medium btn-primary pull-right" %>
<% end %>

app/views/shared/_new_document_modal.html.erb
<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>
<% if !@micropost.errors.any? %>
  <div class="modal fade" id="new_document_modal" tabindex="-1" role="dialog" 
    aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Add document</h4>
        </div>
        <div class="modal-body">
          <%# Render the new document form (passing modal => true to enable remote => true) %>
          <%= render 'shared/document_form', modal: true %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<% if @micropost && @micropost.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@micropost.errors.count, "error") %>.
    </div>
    <ul>
    <% @micropost.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @document && @document.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@document.errors.count, "error") %>.
    </div>
    <ul>
    <% @document.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%# @micropost1 = Micropost.new %>
<%#= render partial: 'shared/error_messages', object: => micropost %>
<%#= render partial: 'shared/error_messages', object: => document %>
<%# content = "This is a hard-wired post." %>
<%# micropost_content = "" %>
<%= form_tag(microposts_path, method: "post") do %>
  <%= text_area_tag :content %>
  <%= @micropost1 = Micropost.new(:user => @user, :content => :content) %>
  <%= hidden_field_tag(@micropost1) %>
  <%= submit_tag("Post", name: "post", :data => :micropost, class: "btn btn-large btn-primary") %>
<% end %>
  <%#= text_area_tag :content, size: "20x30" %>
  <%#= button_to "Post", { action: "create" , controller: :microposts, micropost: {content: :content , user: @user} } %> 
<%#= form_tag(microposts_path, method: "post") do %>
  <%#= text_field_tag(:content) %>
  <%#= hash_as_hidden_fields({:micropost => user: @user}) %>
  <%#= hidden_field_tag(:micropost, :user, value: @user) %>
  <%#= hidden_field_tag(:micropost, :content, value: :content) %>
  <%#= submit_tag("Post", name: "post", :data => :micropost, class: "btn btn-large btn-primary") %>
<%# end %>

<%# @document1 = Document.new %>
<%#= render partial: 'shared/error_messages', object: @document1 %>
<%# document_url = "" %>
<%# document_url = "http://www.arxiv.org/pdf/1111.123.pdf" %>
<%#= button_to "Add document", { action: "create" , controller: :documents, document: {url: document_url, user: @user} } %> 

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "post") %>,
  <%= pluralize(current_user.documents.count, "document") %>
</span>